<?php
include("templates/$template/blocks/mymenu.php");
//include("templates/$template/blocks/sitemap.php");
include("templates/$template/blocks/random.php");
//include("templates/$template/blocks/bannerleft.php");
include("templates/$template/blocks/category.php");
//include("templates/$template/blocks/ad1.php");
//include("templates/$template/blocks/ad2.php");
include("templates/$template/blocks/topgames.php");
include("templates/$template/blocks/topusers.php");
include("templates/$template/blocks/latest.php");
include("templates/$template/blocks/links.php");
include("templates/$template/blocks/stats.php");
?>